---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{.Values.name}}
  namespace: {{.Values.namespace}}
  labels:
    component: {{.Values.name}}
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
